time:
  # how often do events occur? should follow the regex pattern \d+?(?:d|w|M|Y)
  # d: days
  # w: weeks
  # M: months
  # Y: years
  granularity: 1M
  # time period in years
  period: 30

initialState:
  date: 2000-01-01
  values:
  - type: cash
    value: 100
    name: Savings
  - type: constant-growth-asset
    name: CD Savings
    value: 500
    appreciation: 0.05

# optional
scheduledStateUpdates:
- schedule:
    startDate: 2030-05-15
    endDate: 2040-04-30
  type: cash
  value: 5000
  name: inheritance
